---
AWSTemplateFormatVersion: '2010-09-09'
Description: IAM roles for LTTM project

Parameters:
  MainAccountId:
    Description: Main Account ID - the one where CloudTrail Event Data Store is
    Type: String

Resources:
  LttmCloudTrailLakeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LttmCloudTrailLakeRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: LakeFederationTrustEntity
            Effect: Allow
            Principal:
              Service: lakeformation.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref MainAccountId
      Path: /
      Policies:
        - PolicyName: LttmCloudTrailLakePerm
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: LakeFederationEDSDataAccess
                Effect: Allow
                Action:
                  - cloudtrail:GetEventDataStoreData
                  - cloudtrail:StartQuery
                  - cloudtrail:GetQueryResults
                  - cloudtrail:CancelQuery
                  - cloudtrail:ListQueries
                  - cloudtrail:DescribeQuery
                Resource: !Sub "arn:aws:cloudtrail:eu-central-1:${MainAccountId}:eventdatastore/*"
              - Sid: OrganizationTrailAccess
                Effect: Allow
                Action:
                  - cloudtrail:GetTrail
                  - cloudtrail:ListTrails
                  - cloudtrail:GetTrailStatus
                  - organizations:ListAccounts
                  - organizations:DescribeOrganization
                Resource: "*"

  # IAM role for Lex chatbot
  LttmLexBotRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LttmLexBotRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lexv2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: LttmLexBotPerm
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - lex:RecognizeText
                  - lex:RecognizeUtterance
                Resource: "*"
  
  # IAM role for Lambda function
  LttmLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LttmLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LttmBedrockPerm
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:*
                  - bedrock-runtime:*
                Resource: "*"
        - PolicyName: LttmCloudTrailPerm
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudtrail:*
                Resource: "*"
        - PolicyName: LttmLexInvokePerm
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lex:*
                Resource: "*"
        - PolicyName: LttmInvokeAnyLambdaInAccount
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Sub "arn:aws:lambda:eu-central-1:${MainAccountId}:function:*"
        # - PolicyName: LTTM-Bedrock-Explicit
        #   PolicyDocument:
        #     Version: '2012-10-17'
        #     Statement:
        #       - Effect: Allow
        #         Action:
        #           - bedrock:InvokeModel
        #           - bedrock:InvokeModelWithResponseStream
        #           - bedrock:Converse
        #         Resource: "arn:aws:bedrock:us-west-2::foundation-model/anthropic.claude-3-7-sonnet-20250219-v1:0"

Outputs:
  LttmCloudTrailLakeRoleArn:
    Value:
      !GetAtt LttmCloudTrailLakeRole.Arn
    Export:
      Name: LttmCloudTrailLakeRoleArn

  LttmLexBotRoleArn:    
    Value:
      !GetAtt LttmLexBotRole.Arn
    Export:
      Name: LttmLexBotRoleArn
 
  LttmLambdaRoleArn:
    Value:
      !GetAtt LttmLambdaRole.Arn
    Export:
      Name: LttmLambdaRoleArn
