# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Michal Salanci

---
AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for LTTM Lambda artifacts (layers, functions). Used for all versions of LTTM project

Parameters:
  LttmArtifactsBucketName:
    Type: String
    Default: lttm-artifacts-bucket
    Description: S3 bucket name for Lambda layers and deployment artifacts

Resources:
  LttmArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref LttmArtifactsBucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  LttmArtifactsBucket:
    Value: !Ref LttmArtifactsBucket
    Export:
      Name: LttmArtifactsBucket

  LttmArtifactsBucketArn:
    Value: !GetAtt LttmArtifactsBucket.Arn
    Export:
      Name: LttmArtifactsBuckettArn
