# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Michal Salanci
---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudTrail Lake for LTTM projetct and all its version, gathering CloudTrail logs from all accounts within AWS Organization

Resources:
  LttmCloudTrailLake:
    Type: AWS::CloudTrail::EventDataStore
    Properties:
      Name: LttmCloudTrailLake
      AdvancedEventSelectors:
        - Name: Management events selector
          FieldSelectors:
            - Field: eventCategory
              Equals:
                - Management
        # - Name: Data events selector
        #   FieldSelectors:
        #     - Field: eventCategory
        #       Equals:
        #         - Data
        #     # Optional: Filter to specific service
        #     # - Field: eventSource
        #     #   Equals:
        #     #     - s3.amazonaws.com
        #     #     - lambda.amazonaws.com
        # - Name: Insights events selector
        #   FieldSelectors:
        #     - Field: eventCategory
        #       Equals:
        #         - Insights

      MultiRegionEnabled: true
      OrganizationEnabled: true
      # RetentionPeriod: 366 # 1y default
      # RetentionPeriod: 730  # 2y
      RetentionPeriod: 1095 # 3y
      TerminationProtectionEnabled: true
      BillingMode: EXTENDABLE_RETENTION_PRICING
      FederationEnabled: true
      FederationRoleArn: !ImportValue LttmCloudTrailLakeRoleArn
      IngestionEnabled: true

Outputs:
  EventDataStoreArn:
    Value: 
      !GetAtt LttmCloudTrailLake.EventDataStoreArn
    Export:
      Name: EventDataStoreArn

  EventDataStoreId:
    Description: "The ID of the CloudTrail Lake Event Data Store"
    Value: 
      !Select [1, !Split ["eventdatastore/", !GetAtt LttmCloudTrailLake.EventDataStoreArn]]
    Export:
      Name: EventDataStoreId

  EventDataStoreRegion:
    Description: "Region where the CloudTrail Lake Event Data Store was created"
    Value: !Ref "AWS::Region"
    Export:
      Name: EventDataStoreRegion
