---
AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Layer for LTTMv2 utils

Parameters:
  LambdaZipVersion:
    Type: String
    Description: S3 object version for the Lambda zip file, is populated by deploy_lambnda.sh during deployment

Resources:
  LttmUtilsLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: lttm_utils
      Description: Utility functions for LTTMv2
      CompatibleRuntimes:
        - python3.12
        # - python3.13
      Content:
        S3Bucket: !ImportValue LttmArtifactsBucket
        S3Key: lttmv2/layers/lttm_utils.zip
        S3ObjectVersion: !Ref LambdaZipVersion

Outputs:
  LttmUtilsLayerArn:
    Value: !Ref LttmUtilsLayer
    Export:
      Name: LttmUtilsLayerArn
