---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create CloudTrailLogBot with account ID required for all intents

Parameters:
  # Use as many account IDs as you have. This project is useing 3
  AccountId1:
    Description: Account ID 1
    Type: String
    Default: "123456789012"  # Replace with real account ID in deployment

  AccountId2:
    Description: Account ID 2
    Type: String
    Default: "234567890123"  # Replace with real account ID in deployment

  AccountId3:
    Description: Account ID 3
    Type: String
    Default: "345678901234"  # Replace with real account ID in deployment

Resources:
  CloudTrailLogBot:
    Type: AWS::Lex::Bot
    Properties:
      Name: LTTLex
      RoleArn: !ImportValue LexBotRoleArn
      DataPrivacy:
        ChildDirected: false
      IdleSessionTTLInSeconds: 300
      AutoBuildBotLocales: true
      Description: "Bot for CloudTrail logs analysis"
      BotLocales:
        - LocaleId: en_US
          # NluConfidenceThreshold: 0.40
          NluConfidenceThreshold: 0.30
          VoiceSettings:
            VoiceId: Salli
          SlotTypes:
            - Name: UsernameSlotType
              SlotTypeValues:
                - SampleValue: { Value: "admin" }
                - SampleValue: { Value: "john" }
                - SampleValue: { Value: "ManagementAdmin" }
                - SampleValue: { Value: "AliceAdmin" }
                - SampleValue: { Value: "bob.builder" }
                - SampleValue: { Value: "root" }
                - SampleValue: { Value: "finance.user" }
              ValueSelectionSetting:
                ResolutionStrategy: ORIGINAL_VALUE

            - Name: IPAddressSlotType
              SlotTypeValues:
                # - SampleValue: { Value: "192.168.1.1" }
                # - SampleValue: { Value: "10.0.0.1" }
                - SampleValue: { Value: "8.8.8.8" } # Public IP
                - SampleValue: { Value: "18.184.81.91" } # Typical AWS IP
                - SampleValue: { Value: "192.168.1.1" } # Private IP
              ValueSelectionSetting:
                ResolutionStrategy: ORIGINAL_VALUE

            - Name: TimeframeHoursSlotType
              SlotTypeValues:
                # - SampleValue: { Value: "24" }
                # - SampleValue: { Value: "48" }
                - SampleValue: { Value: "1" }
              ValueSelectionSetting:
                ResolutionStrategy: ORIGINAL_VALUE

            - Name: AccountIdSlotType
              SlotTypeValues:
                - SampleValue:
                    Value: !Sub "${AccountId1}"
                - SampleValue:
                    Value: !Sub "${AccountId2}"
                - SampleValue:
                    Value: !Sub "${AccountId3}"
              ValueSelectionSetting:
                ResolutionStrategy: ORIGINAL_VALUE

          Intents:
            - Name: ListApiCallsByUserIntent
              Description: "List API calls by a user"
              SampleUtterances:
                - Utterance: "List all API calls made by {username} in account {accountid}"
                - Utterance: "Show actions performed by {username} in account {accountid}"
                - Utterance: "Track API usage for {username} in {accountid}"
                - Utterance: "List API calls for {username}"
                - Utterance: "Track activities for {username}"
              Slots:
                - Name: username
                  SlotTypeName: UsernameSlotType
                  ValueElicitationSetting:
                    SlotConstraint: Optional
                    PromptSpecification:
                      MessageGroupsList:
                        - Message:
                            PlainTextMessage:
                              Value: "Which user are you interested in?"
                      MaxRetries: 2
                    DefaultValueSpecification:
                      DefaultValueList:
                        - DefaultValue: "ManagementAdmin"
                - Name: accountid
                  SlotTypeName: AccountIdSlotType
                  ValueElicitationSetting:
                    # SlotConstraint: Optional
                    SlotConstraint: Required
                    PromptSpecification:
                      MessageGroupsList:
                        - Message:
                            PlainTextMessage:
                              Value: "Which AWS account should I check?"
                      MaxRetries: 2
                    DefaultValueSpecification:
                      DefaultValueList:
                        - DefaultValue: !Ref AccountId1
              SlotPriorities:
                - Priority: 1
                  SlotName: username
                - Priority: 2
                  SlotName: accountid
              DialogCodeHook:
                Enabled: true
              FulfillmentCodeHook:
                Enabled: true

            - Name: ShowActivitiesFromIPAddressIntent
              Description: "Show activities from a given IP address"
              SampleUtterances:
                - Utterance: "Show activities from IP address {ipaddress} in account {accountid}"
                - Utterance: "List activity from {ipaddress} in account {accountid}"
                - Utterance: "Display CloudTrail events from {ipaddress} in account {accountid}"
                - Utterance: "Find operations originating from {ipaddress} in account {accountid}"
                - Utterance: "Get all API calls from {ipaddress} in account {accountid}"
                - Utterance: "Audit events for IP {ipaddress} in account {accountid}"
              Slots:
                - Name: ipaddress
                  SlotTypeName: IPAddressSlotType
                  ValueElicitationSetting:
                    SlotConstraint: Optional
                    PromptSpecification:
                      MessageGroupsList:
                        - Message:
                            PlainTextMessage:
                              Value: "Which IP address are you interested in?"
                      MaxRetries: 2
                    DefaultValueSpecification:
                      DefaultValueList:
                        - DefaultValue: "192.168.1.1"
                - Name: accountid
                  SlotTypeName: AccountIdSlotType
                  ValueElicitationSetting:
                    # SlotConstraint: Optional
                    SlotConstraint: Required
                    PromptSpecification:
                      MessageGroupsList:
                        - Message:
                            PlainTextMessage:
                              Value: "Which AWS account should I check?"
                      MaxRetries: 2
                    DefaultValueSpecification:
                      DefaultValueList:
                        - DefaultValue: !Ref AccountId1
              SlotPriorities:
                - Priority: 1
                  SlotName: ipaddress
                - Priority: 2
                  SlotName: accountid
              DialogCodeHook:
                Enabled: true
              FulfillmentCodeHook:
                Enabled: true

            - Name: FindSuccessfulOperationsIntent
              Description: "Find successful operations in CloudTrail"
              SampleUtterances:
                - Utterance: "Find successful API operations in account {accountid}"
                - Utterance: "Show successful actions in account {accountid}"
                - Utterance: "List successful CloudTrail events in account {accountid}"
                - Utterance: "Track successful API calls in account {accountid}"
                - Utterance: "Get successful AWS operations in account {accountid}"
              Slots:
                - Name: accountid
                  SlotTypeName: AccountIdSlotType
                  ValueElicitationSetting:
                    SlotConstraint: Required
                    PromptSpecification:
                      MessageGroupsList:
                        - Message:
                            PlainTextMessage:
                              Value: "Which AWS account should I check?"
                      MaxRetries: 2
                    DefaultValueSpecification:
                      DefaultValueList:
                        - DefaultValue: !Ref AccountId1
              SlotPriorities:
                - Priority: 1
                  SlotName: accountid
              DialogCodeHook:
                Enabled: true
              FulfillmentCodeHook:
                Enabled: true

            - Name: FindFailedOperationsIntent
              Description: "Find failed operations in CloudTrail"
              SampleUtterances:
                - Utterance: "Find failed API operations in account {accountid}"
                - Utterance: "Show error responses in account {accountid}"
                - Utterance: "List failed CloudTrail events in account {accountid}"
                - Utterance: "Track API failures in account {accountid}"
                - Utterance: "Get failed AWS operations in account {accountid}"
              Slots:
                - Name: accountid
                  SlotTypeName: AccountIdSlotType
                  ValueElicitationSetting:
                    # SlotConstraint: Optional
                    SlotConstraint: Required
                    PromptSpecification:
                      MessageGroupsList:
                        - Message:
                            PlainTextMessage:
                              Value: "Which AWS account should I check?"
                      MaxRetries: 2
                    DefaultValueSpecification:
                      DefaultValueList:
                        - DefaultValue: !Ref AccountId1
              SlotPriorities:
                - Priority: 1
                  SlotName: accountid
              DialogCodeHook:
                Enabled: true
              FulfillmentCodeHook:
                Enabled: true

            - Name: SummarizeLoginActivitiesIntent
              Description: "Summarize login activities over time"
              SampleUtterances:
                - Utterance: "Summarize login activities for the past {timeframehours} hours"
                - Utterance: "Show login summary for last {timeframehours} hours"
                - Utterance: "Give me an overview of logins in last {timeframehours} hours"
                - Utterance: "Track login attempts in the past {timeframehours} hours"
                - Utterance: "List all user logins from the last {timeframehours} hours"
                - Utterance: "Summarize user sign-ins for {timeframehours} hours"
              Slots:
                - Name: timeframehours
                  SlotTypeName: TimeframeHoursSlotType
                  ValueElicitationSetting:
                    SlotConstraint: Optional
                    PromptSpecification:
                      MessageGroupsList:
                        - Message:
                            PlainTextMessage:
                              Value: "How many hours back should I check?"
                      MaxRetries: 2
                - Name: accountid
                  SlotTypeName: AccountIdSlotType
                  ValueElicitationSetting:
                    SlotConstraint: Required
                    PromptSpecification:
                      MessageGroupsList:
                        - Message:
                            PlainTextMessage:
                              Value: "Which AWS account should I check?"
                      MaxRetries: 2
                    DefaultValueSpecification:
                      DefaultValueList:
                        - DefaultValue: !Ref AccountId1
              SlotPriorities:
                - Priority: 1
                  SlotName: timeframehours
                - Priority: 2
                  SlotName: accountid
              DialogCodeHook:
                Enabled: true
              FulfillmentCodeHook:
                Enabled: true

            - Name: ListUsersInAccountIntent
              Description: "List distinct users observed in the CloudTrail logs"
              SampleUtterances:
                - Utterance: "list all users in account {accountid}"
                - Utterance: "list all user IDs in account {accountid}"
                - Utterance: "show all users who accessed account {accountid}"
              Slots:
                - Name: accountid
                  SlotTypeName: AccountIdSlotType
                  ValueElicitationSetting:
                    SlotConstraint: Required
                    PromptSpecification:
                      MessageGroupsList:
                        - Message:
                            PlainTextMessage:
                              Value: "Which AWS account should I check?"
                      MaxRetries: 2
                    DefaultValueSpecification:
                      DefaultValueList:
                        - DefaultValue: !Ref AccountId1
              SlotPriorities:
                - Priority: 1
                  SlotName: accountid
              DialogCodeHook:
                Enabled: true
              FulfillmentCodeHook:
                Enabled: true
            
            - Name: ListSuccessfulLoginsIntent
              Description: "List successful login activities"
              SampleUtterances:
                - Utterance: "List successful logins in account {accountid}"
                - Utterance: "Show successful sign-ins for account {accountid}"
                - Utterance: "Give me successful login attempts in account {accountid}"
                - Utterance: "List recent successful logins in {accountid}"
              Slots:
                - Name: accountid
                  SlotTypeName: AccountIdSlotType
                  ValueElicitationSetting:
                    SlotConstraint: Required
                    PromptSpecification:
                      MessageGroupsList:
                        - Message:
                            PlainTextMessage:
                              Value: "Which AWS account should I check?"
                      MaxRetries: 2
                    DefaultValueSpecification:
                      DefaultValueList:
                        - DefaultValue: !Ref AccountId1
              SlotPriorities:
                - Priority: 1
                  SlotName: accountid
              DialogCodeHook:
                Enabled: true
              FulfillmentCodeHook:
                Enabled: true

            - Name: ListUserIPAddressesIntent
              Description: "List IP addresses used by users"
              SampleUtterances:
                - Utterance: "Give me users IP addresses"
                - Utterance: "List IP addresses used by users"
                - Utterance: "Show all user IP addresses"
                - Utterance: "What IP addresses did users log in from"
                - Utterance: "List all source IP addresses"
              Slots:
                - Name: accountid
                  SlotTypeName: AccountIdSlotType
                  ValueElicitationSetting:
                    SlotConstraint: Required
                    PromptSpecification:
                      MessageGroupsList:
                        - Message:
                            PlainTextMessage:
                              Value: "Which AWS account should I check?"
                      MaxRetries: 2
                    DefaultValueSpecification:
                      DefaultValueList:
                        - DefaultValue: !Ref AccountId1
              SlotPriorities:
                - Priority: 1
                  SlotName: accountid
              DialogCodeHook:
                Enabled: true
              FulfillmentCodeHook:
                Enabled: true

            - Name: ListFailedLoginsIntent
              Description: "List failed login activities"
              SampleUtterances:
                - Utterance: "List failed logins in account {accountid}"
                - Utterance: "List unsuccessful logins in account {accountid}"
                - Utterance: "Show failed sign-ins for account {accountid}"
                - Utterance: "Show unsuccessful sign-ins for account {accountid}"
                - Utterance: "Give me failed login attempts in account {accountid}"
                - Utterance: "Give me unsuccessful login attempts in account {accountid}"
              Slots:
                - Name: accountid
                  SlotTypeName: AccountIdSlotType
                  ValueElicitationSetting:
                    SlotConstraint: Required
                    PromptSpecification:
                      MessageGroupsList:
                        - Message:
                            PlainTextMessage:
                              Value: "Which AWS account should I check?"
                      MaxRetries: 2
                    DefaultValueSpecification:
                      DefaultValueList:
                        - DefaultValue: !Ref AccountId1
              SlotPriorities:
                - Priority: 1
                  SlotName: accountid
              DialogCodeHook:
                Enabled: true
              FulfillmentCodeHook:
                Enabled: true

            - Name: FallbackIntent
              ParentIntentSignature: AMAZON.FallbackIntent
              IntentClosingSetting:
                ClosingResponse:
                  MessageGroupsList:
                    - Message:
                        PlainTextMessage:
                          Value: "I'm sorry, I didn't understand that. Please rephrase."

  BotVersion:
    Type: AWS::Lex::BotVersion
    DependsOn: CloudTrailLogBot
    Properties:
      BotId: !Ref CloudTrailLogBot
      BotVersionLocaleSpecification:
        - LocaleId: en_US
          BotVersionLocaleDetails:
            SourceBotVersion: DRAFT

  ProdAlias:
    Type: AWS::Lex::BotAlias
    DependsOn: BotVersion
    Properties:
      BotAliasName: PROD
      BotId: !Ref CloudTrailLogBot
      BotAliasLocaleSettings:
        - LocaleId: en_US
          BotAliasLocaleSetting:
            Enabled: true
            CodeHookSpecification:
              LambdaCodeHook:
                LambdaArn: !ImportValue LTTMMainFunctionArn
                CodeHookInterfaceVersion: "1.0"
      BotVersion: !GetAtt BotVersion.BotVersion
      SentimentAnalysisSettings:
        DetectSentiment: false

  LexV2Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue LTTMMainFunctionArn
      Action: lambda:InvokeFunction
      Principal: lexv2.amazonaws.com
      SourceArn: !Sub "arn:aws:lex:eu-central-1:${AccountId1}:bot-alias/*"
